// Generated by scripts/generate-constants.mjs from src/SwapVMKernel.sol,
// src/SwapVMMiniVM.sol and the frozen v1.1 section 23. Do not edit by hand;
// `npm run generate:constants` updates it.
export const RECEIPT_VERSION = 1 as const;
export const RECEIPT_FLAGS_V1 = 0 as const;
export const KERNEL_EMITTER_ID =
  "0xff00000000000000000000000000000000000000000000000000000000000001" as const;
export const WORLD_EXECUTION_SIGNATURE =
  "WorldExecution(bytes32,bytes32,uint32,uint256,uint256,uint256)" as const;
export const WORLD_EXECUTION_TOPIC =
  "0x3112cedead241c6530b184adc877ddaf0a4157aa13a4a0988b4bde6ce794defc" as const;
export const MINI_CONTRACT_DEPLOYED_SIGNATURE =
  "MiniContractDeployed(bytes32,bytes32,bytes32)" as const;
export const MINI_CONTRACT_DEPLOYED_TOPIC =
  "0x80a1f0b8838c2c604364e05a5ccc199e116f9521077e9f00836dc0b340ac1531" as const;
export const MAX_RECEIPT_RECORDS = 64 as const;
export const MAX_RECORD_TOPICS = 4 as const;
export const MAX_RECORD_DATA_BYTES = 4096 as const;
export const MAX_RECEIPT_PAYLOAD_BYTES = 65536 as const;
export const WORLD_EXECUTION_DATA_BYTES = 192 as const;
export const MINI_CONTRACT_DEPLOYED_DATA_BYTES = 96 as const;
