import { canonicalJson } from "./abi.js";
import type { TinySolAbi, TinySolEventAbi, TinySolScalarType } from "./compiler-types.js";

function tsType(type: TinySolScalarType): string {
  if (type === "bool") return "boolean";
  if (/^(u?)int\d+$/.test(type)) return "bigint";
  return "Hex";
}

function tuple(types: readonly TinySolScalarType[]): string {
  if (types.length === 0) return "void";
  if (types.length === 1) return tsType(types[0]!);
  return `readonly [${types.map(tsType).join(", ")}]`;
}

function decode(type: TinySolScalarType, source: string): string {
  if (type === "bool") return `decodeWord(${source}) !== 0n`;
  const integer = /^(u?)int(\d+)$/.exec(type);
  if (integer?.[1] === "u") return integer[2] === "256" ? `decodeWord(${source})` : `decodeUint(${source}, ${integer[2]})`;
  if (integer !== null) return integer[2] === "256" ? `decodeInt256(${source})` : `decodeInt(${source}, ${integer[2]})`;
  return source;
}

export function generateTypeScriptBindings(abi: TinySolAbi, eventAbi?: TinySolEventAbi): string {
  const lines = [
    "// Generated by @swaputer-labs/tinysol. Do not edit.",
    "export type Hex = `0x${string}`;",
    "export interface TinySolClient { read(target: Hex, calldata: Hex): Promise<Hex>; write(target: Hex, calldata: Hex): Promise<Hex>; }",
    `export const abi = ${canonicalJson(abi)} as const;`,
    `export const events = ${canonicalJson(eventAbi?.events ?? [])} as const;`,
    "function encodeWord(value: bigint | boolean | Hex): string { const raw = typeof value === 'boolean' ? (value ? '1' : '0') : typeof value === 'bigint' ? (value < 0n ? (1n << 256n) + value : value).toString(16) : value.slice(2); if (!/^[0-9a-fA-F]{1,64}$/.test(raw)) throw new Error('TINYSOL_BINDING_WORD'); return raw.toLowerCase().padStart(64, '0'); }",
    "function encodeTypedWord(value: bigint | boolean | Hex, type: string): string { const integer = /^(u?)int(\\d+)$/.exec(type); if (integer !== null) { if (typeof value !== 'bigint') throw new Error('TINYSOL_BINDING_TYPE'); const width = BigInt(integer[2]!); const signed = integer[1] !== 'u'; const minimum = signed ? -(1n << (width - 1n)) : 0n; const maximum = signed ? (1n << (width - 1n)) - 1n : (1n << width) - 1n; if (value < minimum || value > maximum) throw new Error('TINYSOL_BINDING_RANGE'); } return encodeWord(value); }",
    "function words(data: Hex): Hex[] { const raw = data.slice(2); if (raw.length % 64 !== 0) throw new Error('TINYSOL_BINDING_DATA'); return Array.from({length: raw.length / 64}, (_, index) => `0x${raw.slice(index * 64, index * 64 + 64)}` as Hex); }",
    "function decodeWord(value: Hex): bigint { return BigInt(value); }",
    "function decodeInt256(value: Hex): bigint { const word = BigInt(value); return word >= (1n << 255n) ? word - (1n << 256n) : word; }",
    "function decodeUint(value: Hex, width: number): bigint { const decoded = decodeWord(value); if (decoded > (1n << BigInt(width)) - 1n) throw new Error('TINYSOL_BINDING_RANGE'); return decoded; }",
    "function decodeInt(value: Hex, width: number): bigint { const decoded = decodeInt256(value); const bits = BigInt(width - 1); if (decoded < -(1n << bits) || decoded > (1n << bits) - 1n) throw new Error('TINYSOL_BINDING_RANGE'); return decoded; }"
  ];
  for (const fn of abi.functions) {
    const title = `${fn.name[0]!.toUpperCase()}${fn.name.slice(1)}`;
    lines.push(`export type ${title}Args = readonly [${fn.inputs.map(tsType).join(", ")}];`);
    lines.push(`export type ${title}Result = ${tuple(fn.outputs)};`);
    lines.push(`export function encode${title}(args: ${title}Args): Hex { const types = ${canonicalJson(fn.inputs)} as readonly string[]; return \`${fn.selector}\${args.map((value, index) => encodeTypedWord(value, types[index]!)).join('')}\` as Hex; }`);
    const decoded = fn.outputs.length === 0 ? "undefined" : fn.outputs.length === 1 ? decode(fn.outputs[0]!, "values[0]!") : `[${fn.outputs.map((type, index) => decode(type, `values[${index}]!`)).join(", ")}] as const`;
    lines.push(`export function decode${title}(data: Hex): ${title}Result { const values = words(data); if (values.length !== ${fn.outputs.length}) throw new Error('TINYSOL_BINDING_ARITY'); return ${decoded} as ${title}Result; }`);
    const action = fn.view ? "read" : "write";
    lines.push(`export async function ${fn.view ? "read" : "call"}${title}(client: TinySolClient, target: Hex, args: ${title}Args): Promise<${title}Result> { return decode${title}(await client.${action}(target, encode${title}(args))); }`);
  }
  if (abi.errors !== undefined) {
    lines.push(`export const errorSelectors = ${canonicalJson(Object.fromEntries(abi.errors.map((error) => [error.name, error.selector])))} as const;`);
    lines.push("export function errorSelector(data: Hex): Hex { if (data.length < 10) throw new Error('TINYSOL_BINDING_ERROR'); return data.slice(0, 10) as Hex; }");
  }
  for (const error of abi.errors ?? []) {
    const title = `${error.name[0]!.toUpperCase()}${error.name.slice(1)}`;
    lines.push(`export interface ${title}Error { readonly name: '${error.name}'; ${error.inputs.map((type, index) => `readonly field${index}: ${tsType(type)};`).join(" ")} }`);
    const fields = error.inputs.map((type, index) => `field${index}: ${decode(type, `values[${index}]!`)}`);
    lines.push(`export function decode${title}Error(data: Hex): ${title}Error { if (errorSelector(data) !== '${error.selector}') throw new Error('TINYSOL_BINDING_ERROR_SELECTOR'); const values = words(\`0x\${data.slice(10)}\` as Hex); if (values.length !== ${error.inputs.length}) throw new Error('TINYSOL_BINDING_ARITY'); return { name: '${error.name}', ${fields.join(", ")} }; }`);
  }
  for (const event of eventAbi?.events ?? []) {
    const title = `${event.name[0]!.toUpperCase()}${event.name.slice(1)}`;
    lines.push(`export interface ${title}Event { ${event.fields.map((field) => `readonly ${field.name}: ${tsType(field.type)};`).join(" ")} }`);
    const values = event.fields.map((field) => {
      const source = field.indexed ? `topics[${field.position}]!` : `dataWords[${field.position}]!`;
      return `${field.name}: ${decode(field.type, source)}`;
    });
    lines.push(`export function decode${title}Event(topics: readonly Hex[], data: Hex): ${title}Event { if (topics[0] !== '${event.topic0}') throw new Error('TINYSOL_BINDING_TOPIC'); const dataWords = words(data); return { ${values.join(", ")} }; }`);
  }
  return `${lines.join("\n")}\n`;
}
