// Generated by scripts/generate-compiler-identity.mjs. Do not edit manually.
export const COMPILER_SOURCE_FINGERPRINT = "0xf003179b10cffcb58d88f6143ce2846a398c6b35737127c5482c76066dbdadf7" as const;
export const COMPILER_DEPENDENCY_LOCK_SHA256 = "e17e5e5e5243f8460cb6cacb32d24063cb85536aa31b1c56eab24345301a7f42" as const;
