// Generated from docs/spec/SwapVM-ISA-v2.json by scripts/generate-isa.mjs.
// Do not edit manually.

export const ISA_VERSION = 2 as const;
export const ISA_FILE_KECCAK = "0x5958f1a3baf744e5ed92f096a964ee14779db2e32e70a2982c53080eb3cd92c2" as const;
export const ISA_FILE_SHA256 = "e1c194b49a0275ce052758d18c834b0a6c8fedbb3932b0cf378b725c992ed389" as const;
export const ISA_WORD_BITS = 256 as const;
export const ISA_BYTE_ORDER = "big-endian" as const;

export const GENERATED_INSTRUCTIONS = [
  {
    "opcode": 0,
    "mnemonic": "STOP",
    "immediateBytes": 0,
    "pops": 0,
    "pushes": 0,
    "staticAllowed": true,
    "stackSignature": "()->()",
    "semantics": "successful frame halt with empty output",
    "width": 1
  },
  {
    "opcode": 1,
    "mnemonic": "ADD",
    "immediateBytes": 0,
    "pops": 2,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "(arg1,arg0)->(result0)",
    "semantics": "a+b modulo 2^256",
    "width": 1
  },
  {
    "opcode": 2,
    "mnemonic": "MUL",
    "immediateBytes": 0,
    "pops": 2,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "(arg1,arg0)->(result0)",
    "semantics": "a*b modulo 2^256",
    "width": 1
  },
  {
    "opcode": 3,
    "mnemonic": "SUB",
    "immediateBytes": 0,
    "pops": 2,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "(arg1,arg0)->(result0)",
    "semantics": "a-b modulo 2^256",
    "width": 1
  },
  {
    "opcode": 4,
    "mnemonic": "DIV",
    "immediateBytes": 0,
    "pops": 2,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "(arg1,arg0)->(result0)",
    "semantics": "unsigned a/b; zero if b is zero",
    "width": 1
  },
  {
    "opcode": 5,
    "mnemonic": "SDIV",
    "immediateBytes": 0,
    "pops": 2,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "(arg1,arg0)->(result0)",
    "semantics": "signed a/b; zero if b is zero; minimum/-1 returns minimum",
    "width": 1
  },
  {
    "opcode": 6,
    "mnemonic": "MOD",
    "immediateBytes": 0,
    "pops": 2,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "(arg1,arg0)->(result0)",
    "semantics": "unsigned a%b; zero if b is zero",
    "width": 1
  },
  {
    "opcode": 7,
    "mnemonic": "SMOD",
    "immediateBytes": 0,
    "pops": 2,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "(arg1,arg0)->(result0)",
    "semantics": "signed remainder with sign of a; zero if b is zero",
    "width": 1
  },
  {
    "opcode": 8,
    "mnemonic": "ADDMOD",
    "immediateBytes": 0,
    "pops": 3,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "(a,b,m)->result",
    "semantics": "(a+b)%m at unbounded intermediate precision; zero if m is zero",
    "width": 1
  },
  {
    "opcode": 9,
    "mnemonic": "MULMOD",
    "immediateBytes": 0,
    "pops": 3,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "(a,b,m)->result",
    "semantics": "(a*b)%m at unbounded intermediate precision; zero if m is zero",
    "width": 1
  },
  {
    "opcode": 10,
    "mnemonic": "EXP",
    "immediateBytes": 0,
    "pops": 2,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "(arg1,arg0)->(result0)",
    "semantics": "a**b modulo 2^256",
    "width": 1
  },
  {
    "opcode": 16,
    "mnemonic": "LT",
    "immediateBytes": 0,
    "pops": 2,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "(arg1,arg0)->(result0)",
    "semantics": "one iff unsigned a<b",
    "width": 1
  },
  {
    "opcode": 17,
    "mnemonic": "GT",
    "immediateBytes": 0,
    "pops": 2,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "(arg1,arg0)->(result0)",
    "semantics": "one iff unsigned a>b",
    "width": 1
  },
  {
    "opcode": 18,
    "mnemonic": "SLT",
    "immediateBytes": 0,
    "pops": 2,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "(arg1,arg0)->(result0)",
    "semantics": "one iff signed a<b",
    "width": 1
  },
  {
    "opcode": 19,
    "mnemonic": "SGT",
    "immediateBytes": 0,
    "pops": 2,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "(arg1,arg0)->(result0)",
    "semantics": "one iff signed a>b",
    "width": 1
  },
  {
    "opcode": 20,
    "mnemonic": "EQ",
    "immediateBytes": 0,
    "pops": 2,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "(arg1,arg0)->(result0)",
    "semantics": "one iff a equals b",
    "width": 1
  },
  {
    "opcode": 21,
    "mnemonic": "ISZERO",
    "immediateBytes": 0,
    "pops": 1,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "(arg0)->(result0)",
    "semantics": "one iff value is zero",
    "width": 1
  },
  {
    "opcode": 22,
    "mnemonic": "AND",
    "immediateBytes": 0,
    "pops": 2,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "(arg1,arg0)->(result0)",
    "semantics": "bitwise and",
    "width": 1
  },
  {
    "opcode": 23,
    "mnemonic": "OR",
    "immediateBytes": 0,
    "pops": 2,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "(arg1,arg0)->(result0)",
    "semantics": "bitwise or",
    "width": 1
  },
  {
    "opcode": 24,
    "mnemonic": "XOR",
    "immediateBytes": 0,
    "pops": 2,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "(arg1,arg0)->(result0)",
    "semantics": "bitwise xor",
    "width": 1
  },
  {
    "opcode": 25,
    "mnemonic": "NOT",
    "immediateBytes": 0,
    "pops": 1,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "(arg0)->(result0)",
    "semantics": "bitwise complement",
    "width": 1
  },
  {
    "opcode": 26,
    "mnemonic": "BYTE",
    "immediateBytes": 0,
    "pops": 2,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "(arg1,arg0)->(result0)",
    "semantics": "byte index b of word a, counted from the most-significant end; zero for b>=32",
    "width": 1
  },
  {
    "opcode": 27,
    "mnemonic": "SHL",
    "immediateBytes": 0,
    "pops": 2,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "(arg1,arg0)->(result0)",
    "semantics": "a shifted left by b; zero for b>=256",
    "width": 1
  },
  {
    "opcode": 28,
    "mnemonic": "SHR",
    "immediateBytes": 0,
    "pops": 2,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "(arg1,arg0)->(result0)",
    "semantics": "unsigned a shifted right by b; zero for b>=256",
    "width": 1
  },
  {
    "opcode": 29,
    "mnemonic": "SAR",
    "immediateBytes": 0,
    "pops": 2,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "(arg1,arg0)->(result0)",
    "semantics": "signed arithmetic a shifted right by b with sign extension",
    "width": 1
  },
  {
    "opcode": 32,
    "mnemonic": "KECCAK256",
    "immediateBytes": 0,
    "pops": 2,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "(size,offset)->hash",
    "semantics": "keccak256(memory[offset:offset+size])",
    "width": 1
  },
  {
    "opcode": 33,
    "mnemonic": "ECRECOVER",
    "immediateBytes": 0,
    "pops": 4,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "(hash,v,r,s)->account",
    "semantics": "recover low-s secp256k1 signer and return tagged EOA AccountId or zero",
    "width": 1
  },
  {
    "opcode": 48,
    "mnemonic": "ADDRESS",
    "immediateBytes": 0,
    "pops": 0,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "()->(result0)",
    "semantics": "active mini-contract AccountId",
    "width": 1
  },
  {
    "opcode": 51,
    "mnemonic": "CALLER",
    "immediateBytes": 0,
    "pops": 0,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "()->(result0)",
    "semantics": "immediate caller AccountId",
    "width": 1
  },
  {
    "opcode": 53,
    "mnemonic": "CALLDATALOAD",
    "immediateBytes": 0,
    "pops": 1,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "(arg0)->(result0)",
    "semantics": "32-byte zero-padded calldata word at offset",
    "width": 1
  },
  {
    "opcode": 54,
    "mnemonic": "CALLDATASIZE",
    "immediateBytes": 0,
    "pops": 0,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "()->(result0)",
    "semantics": "current frame calldata byte length",
    "width": 1
  },
  {
    "opcode": 55,
    "mnemonic": "CALLDATACOPY",
    "immediateBytes": 0,
    "pops": 3,
    "pushes": 0,
    "staticAllowed": true,
    "stackSignature": "(size,source,destination)->()",
    "semantics": "copy calldata[source:source+size] to memory[destination:] with zero padding",
    "width": 1
  },
  {
    "opcode": 61,
    "mnemonic": "RETURNDATASIZE",
    "immediateBytes": 0,
    "pops": 0,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "()->(result0)",
    "semantics": "most recent child return-data byte length",
    "width": 1
  },
  {
    "opcode": 62,
    "mnemonic": "RETURNDATACOPY",
    "immediateBytes": 0,
    "pops": 3,
    "pushes": 0,
    "staticAllowed": true,
    "stackSignature": "(size,source,destination)->()",
    "semantics": "copy child return data; source+size beyond result is exceptional halt",
    "width": 1
  },
  {
    "opcode": 66,
    "mnemonic": "TIMESTAMP",
    "immediateBytes": 0,
    "pops": 0,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "()->(result0)",
    "semantics": "current chain block timestamp",
    "width": 1
  },
  {
    "opcode": 67,
    "mnemonic": "NUMBER",
    "immediateBytes": 0,
    "pops": 0,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "()->(result0)",
    "semantics": "current chain block number",
    "width": 1
  },
  {
    "opcode": 80,
    "mnemonic": "POP",
    "immediateBytes": 0,
    "pops": 1,
    "pushes": 0,
    "staticAllowed": true,
    "stackSignature": "(arg0)->()",
    "semantics": "discard top word",
    "width": 1
  },
  {
    "opcode": 81,
    "mnemonic": "MLOAD",
    "immediateBytes": 0,
    "pops": 1,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "(arg0)->(result0)",
    "semantics": "load 32-byte memory word",
    "width": 1
  },
  {
    "opcode": 82,
    "mnemonic": "MSTORE",
    "immediateBytes": 0,
    "pops": 2,
    "pushes": 0,
    "staticAllowed": true,
    "stackSignature": "(value,offset)->()",
    "semantics": "store 32-byte value at memory offset",
    "width": 1
  },
  {
    "opcode": 83,
    "mnemonic": "MSTORE8",
    "immediateBytes": 0,
    "pops": 2,
    "pushes": 0,
    "staticAllowed": true,
    "stackSignature": "(value,offset)->()",
    "semantics": "store low byte of value at memory offset",
    "width": 1
  },
  {
    "opcode": 84,
    "mnemonic": "SLOAD",
    "immediateBytes": 0,
    "pops": 1,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "(arg0)->(result0)",
    "semantics": "load active contract storage slot",
    "width": 1
  },
  {
    "opcode": 85,
    "mnemonic": "SSTORE",
    "immediateBytes": 0,
    "pops": 2,
    "pushes": 0,
    "staticAllowed": false,
    "stackSignature": "(value,slot)->()",
    "semantics": "store value in active contract storage slot",
    "width": 1
  },
  {
    "opcode": 86,
    "mnemonic": "JUMP",
    "immediateBytes": 0,
    "pops": 1,
    "pushes": 0,
    "staticAllowed": true,
    "stackSignature": "(arg0)->()",
    "semantics": "jump to validated JUMPDEST byte offset",
    "width": 1
  },
  {
    "opcode": 87,
    "mnemonic": "JUMPI",
    "immediateBytes": 0,
    "pops": 2,
    "pushes": 0,
    "staticAllowed": true,
    "stackSignature": "(condition,destination)->()",
    "semantics": "jump to destination iff condition is nonzero",
    "width": 1
  },
  {
    "opcode": 88,
    "mnemonic": "PC",
    "immediateBytes": 0,
    "pops": 0,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "()->(result0)",
    "semantics": "current opcode byte offset",
    "width": 1
  },
  {
    "opcode": 89,
    "mnemonic": "MSIZE",
    "immediateBytes": 0,
    "pops": 0,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "()->(result0)",
    "semantics": "current frame memory size in bytes",
    "width": 1
  },
  {
    "opcode": 91,
    "mnemonic": "JUMPDEST",
    "immediateBytes": 0,
    "pops": 0,
    "pushes": 0,
    "staticAllowed": true,
    "stackSignature": "()->()",
    "semantics": "valid dynamic jump destination",
    "width": 1
  },
  {
    "opcode": 95,
    "mnemonic": "PUSH0",
    "immediateBytes": 0,
    "pops": 0,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "()->(result0)",
    "semantics": "push zero",
    "width": 1
  },
  {
    "opcode": 96,
    "mnemonic": "PUSH1",
    "immediateBytes": 1,
    "pops": 0,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "()->(result0)",
    "semantics": "push big-endian immediate",
    "width": 2
  },
  {
    "opcode": 97,
    "mnemonic": "PUSH2",
    "immediateBytes": 2,
    "pops": 0,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "()->(result0)",
    "semantics": "push big-endian immediate",
    "width": 3
  },
  {
    "opcode": 98,
    "mnemonic": "PUSH3",
    "immediateBytes": 3,
    "pops": 0,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "()->(result0)",
    "semantics": "push big-endian immediate",
    "width": 4
  },
  {
    "opcode": 99,
    "mnemonic": "PUSH4",
    "immediateBytes": 4,
    "pops": 0,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "()->(result0)",
    "semantics": "push big-endian immediate",
    "width": 5
  },
  {
    "opcode": 100,
    "mnemonic": "PUSH5",
    "immediateBytes": 5,
    "pops": 0,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "()->(result0)",
    "semantics": "push big-endian immediate",
    "width": 6
  },
  {
    "opcode": 101,
    "mnemonic": "PUSH6",
    "immediateBytes": 6,
    "pops": 0,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "()->(result0)",
    "semantics": "push big-endian immediate",
    "width": 7
  },
  {
    "opcode": 102,
    "mnemonic": "PUSH7",
    "immediateBytes": 7,
    "pops": 0,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "()->(result0)",
    "semantics": "push big-endian immediate",
    "width": 8
  },
  {
    "opcode": 103,
    "mnemonic": "PUSH8",
    "immediateBytes": 8,
    "pops": 0,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "()->(result0)",
    "semantics": "push big-endian immediate",
    "width": 9
  },
  {
    "opcode": 104,
    "mnemonic": "PUSH9",
    "immediateBytes": 9,
    "pops": 0,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "()->(result0)",
    "semantics": "push big-endian immediate",
    "width": 10
  },
  {
    "opcode": 105,
    "mnemonic": "PUSH10",
    "immediateBytes": 10,
    "pops": 0,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "()->(result0)",
    "semantics": "push big-endian immediate",
    "width": 11
  },
  {
    "opcode": 106,
    "mnemonic": "PUSH11",
    "immediateBytes": 11,
    "pops": 0,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "()->(result0)",
    "semantics": "push big-endian immediate",
    "width": 12
  },
  {
    "opcode": 107,
    "mnemonic": "PUSH12",
    "immediateBytes": 12,
    "pops": 0,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "()->(result0)",
    "semantics": "push big-endian immediate",
    "width": 13
  },
  {
    "opcode": 108,
    "mnemonic": "PUSH13",
    "immediateBytes": 13,
    "pops": 0,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "()->(result0)",
    "semantics": "push big-endian immediate",
    "width": 14
  },
  {
    "opcode": 109,
    "mnemonic": "PUSH14",
    "immediateBytes": 14,
    "pops": 0,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "()->(result0)",
    "semantics": "push big-endian immediate",
    "width": 15
  },
  {
    "opcode": 110,
    "mnemonic": "PUSH15",
    "immediateBytes": 15,
    "pops": 0,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "()->(result0)",
    "semantics": "push big-endian immediate",
    "width": 16
  },
  {
    "opcode": 111,
    "mnemonic": "PUSH16",
    "immediateBytes": 16,
    "pops": 0,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "()->(result0)",
    "semantics": "push big-endian immediate",
    "width": 17
  },
  {
    "opcode": 112,
    "mnemonic": "PUSH17",
    "immediateBytes": 17,
    "pops": 0,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "()->(result0)",
    "semantics": "push big-endian immediate",
    "width": 18
  },
  {
    "opcode": 113,
    "mnemonic": "PUSH18",
    "immediateBytes": 18,
    "pops": 0,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "()->(result0)",
    "semantics": "push big-endian immediate",
    "width": 19
  },
  {
    "opcode": 114,
    "mnemonic": "PUSH19",
    "immediateBytes": 19,
    "pops": 0,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "()->(result0)",
    "semantics": "push big-endian immediate",
    "width": 20
  },
  {
    "opcode": 115,
    "mnemonic": "PUSH20",
    "immediateBytes": 20,
    "pops": 0,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "()->(result0)",
    "semantics": "push big-endian immediate",
    "width": 21
  },
  {
    "opcode": 116,
    "mnemonic": "PUSH21",
    "immediateBytes": 21,
    "pops": 0,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "()->(result0)",
    "semantics": "push big-endian immediate",
    "width": 22
  },
  {
    "opcode": 117,
    "mnemonic": "PUSH22",
    "immediateBytes": 22,
    "pops": 0,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "()->(result0)",
    "semantics": "push big-endian immediate",
    "width": 23
  },
  {
    "opcode": 118,
    "mnemonic": "PUSH23",
    "immediateBytes": 23,
    "pops": 0,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "()->(result0)",
    "semantics": "push big-endian immediate",
    "width": 24
  },
  {
    "opcode": 119,
    "mnemonic": "PUSH24",
    "immediateBytes": 24,
    "pops": 0,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "()->(result0)",
    "semantics": "push big-endian immediate",
    "width": 25
  },
  {
    "opcode": 120,
    "mnemonic": "PUSH25",
    "immediateBytes": 25,
    "pops": 0,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "()->(result0)",
    "semantics": "push big-endian immediate",
    "width": 26
  },
  {
    "opcode": 121,
    "mnemonic": "PUSH26",
    "immediateBytes": 26,
    "pops": 0,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "()->(result0)",
    "semantics": "push big-endian immediate",
    "width": 27
  },
  {
    "opcode": 122,
    "mnemonic": "PUSH27",
    "immediateBytes": 27,
    "pops": 0,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "()->(result0)",
    "semantics": "push big-endian immediate",
    "width": 28
  },
  {
    "opcode": 123,
    "mnemonic": "PUSH28",
    "immediateBytes": 28,
    "pops": 0,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "()->(result0)",
    "semantics": "push big-endian immediate",
    "width": 29
  },
  {
    "opcode": 124,
    "mnemonic": "PUSH29",
    "immediateBytes": 29,
    "pops": 0,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "()->(result0)",
    "semantics": "push big-endian immediate",
    "width": 30
  },
  {
    "opcode": 125,
    "mnemonic": "PUSH30",
    "immediateBytes": 30,
    "pops": 0,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "()->(result0)",
    "semantics": "push big-endian immediate",
    "width": 31
  },
  {
    "opcode": 126,
    "mnemonic": "PUSH31",
    "immediateBytes": 31,
    "pops": 0,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "()->(result0)",
    "semantics": "push big-endian immediate",
    "width": 32
  },
  {
    "opcode": 127,
    "mnemonic": "PUSH32",
    "immediateBytes": 32,
    "pops": 0,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "()->(result0)",
    "semantics": "push big-endian immediate",
    "width": 33
  },
  {
    "opcode": 128,
    "mnemonic": "DUP1",
    "immediateBytes": 0,
    "pops": 0,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "(v1)->(v1,v1)",
    "semantics": "duplicate selected existing stack word; underflow if absent",
    "width": 1
  },
  {
    "opcode": 129,
    "mnemonic": "DUP2",
    "immediateBytes": 0,
    "pops": 0,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "(v2,v1)->(v2,v1,v2)",
    "semantics": "duplicate selected existing stack word; underflow if absent",
    "width": 1
  },
  {
    "opcode": 130,
    "mnemonic": "DUP3",
    "immediateBytes": 0,
    "pops": 0,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "(v3,v2,v1)->(v3,v2,v1,v3)",
    "semantics": "duplicate selected existing stack word; underflow if absent",
    "width": 1
  },
  {
    "opcode": 131,
    "mnemonic": "DUP4",
    "immediateBytes": 0,
    "pops": 0,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "(v4,v3,v2,v1)->(v4,v3,v2,v1,v4)",
    "semantics": "duplicate selected existing stack word; underflow if absent",
    "width": 1
  },
  {
    "opcode": 132,
    "mnemonic": "DUP5",
    "immediateBytes": 0,
    "pops": 0,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "(v5,v4,v3,v2,v1)->(v5,v4,v3,v2,v1,v5)",
    "semantics": "duplicate selected existing stack word; underflow if absent",
    "width": 1
  },
  {
    "opcode": 133,
    "mnemonic": "DUP6",
    "immediateBytes": 0,
    "pops": 0,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "(v6,v5,v4,v3,v2,v1)->(v6,v5,v4,v3,v2,v1,v6)",
    "semantics": "duplicate selected existing stack word; underflow if absent",
    "width": 1
  },
  {
    "opcode": 134,
    "mnemonic": "DUP7",
    "immediateBytes": 0,
    "pops": 0,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "(v7,v6,v5,v4,v3,v2,v1)->(v7,v6,v5,v4,v3,v2,v1,v7)",
    "semantics": "duplicate selected existing stack word; underflow if absent",
    "width": 1
  },
  {
    "opcode": 135,
    "mnemonic": "DUP8",
    "immediateBytes": 0,
    "pops": 0,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "(v8,v7,v6,v5,v4,v3,v2,v1)->(v8,v7,v6,v5,v4,v3,v2,v1,v8)",
    "semantics": "duplicate selected existing stack word; underflow if absent",
    "width": 1
  },
  {
    "opcode": 136,
    "mnemonic": "DUP9",
    "immediateBytes": 0,
    "pops": 0,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "(v9,v8,v7,v6,v5,v4,v3,v2,v1)->(v9,v8,v7,v6,v5,v4,v3,v2,v1,v9)",
    "semantics": "duplicate selected existing stack word; underflow if absent",
    "width": 1
  },
  {
    "opcode": 137,
    "mnemonic": "DUP10",
    "immediateBytes": 0,
    "pops": 0,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "(v10,v9,v8,v7,v6,v5,v4,v3,v2,v1)->(v10,v9,v8,v7,v6,v5,v4,v3,v2,v1,v10)",
    "semantics": "duplicate selected existing stack word; underflow if absent",
    "width": 1
  },
  {
    "opcode": 138,
    "mnemonic": "DUP11",
    "immediateBytes": 0,
    "pops": 0,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "(v11,v10,v9,v8,v7,v6,v5,v4,v3,v2,v1)->(v11,v10,v9,v8,v7,v6,v5,v4,v3,v2,v1,v11)",
    "semantics": "duplicate selected existing stack word; underflow if absent",
    "width": 1
  },
  {
    "opcode": 139,
    "mnemonic": "DUP12",
    "immediateBytes": 0,
    "pops": 0,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "(v12,v11,v10,v9,v8,v7,v6,v5,v4,v3,v2,v1)->(v12,v11,v10,v9,v8,v7,v6,v5,v4,v3,v2,v1,v12)",
    "semantics": "duplicate selected existing stack word; underflow if absent",
    "width": 1
  },
  {
    "opcode": 140,
    "mnemonic": "DUP13",
    "immediateBytes": 0,
    "pops": 0,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "(v13,v12,v11,v10,v9,v8,v7,v6,v5,v4,v3,v2,v1)->(v13,v12,v11,v10,v9,v8,v7,v6,v5,v4,v3,v2,v1,v13)",
    "semantics": "duplicate selected existing stack word; underflow if absent",
    "width": 1
  },
  {
    "opcode": 141,
    "mnemonic": "DUP14",
    "immediateBytes": 0,
    "pops": 0,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "(v14,v13,v12,v11,v10,v9,v8,v7,v6,v5,v4,v3,v2,v1)->(v14,v13,v12,v11,v10,v9,v8,v7,v6,v5,v4,v3,v2,v1,v14)",
    "semantics": "duplicate selected existing stack word; underflow if absent",
    "width": 1
  },
  {
    "opcode": 142,
    "mnemonic": "DUP15",
    "immediateBytes": 0,
    "pops": 0,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "(v15,v14,v13,v12,v11,v10,v9,v8,v7,v6,v5,v4,v3,v2,v1)->(v15,v14,v13,v12,v11,v10,v9,v8,v7,v6,v5,v4,v3,v2,v1,v15)",
    "semantics": "duplicate selected existing stack word; underflow if absent",
    "width": 1
  },
  {
    "opcode": 143,
    "mnemonic": "DUP16",
    "immediateBytes": 0,
    "pops": 0,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "(v16,v15,v14,v13,v12,v11,v10,v9,v8,v7,v6,v5,v4,v3,v2,v1)->(v16,v15,v14,v13,v12,v11,v10,v9,v8,v7,v6,v5,v4,v3,v2,v1,v16)",
    "semantics": "duplicate selected existing stack word; underflow if absent",
    "width": 1
  },
  {
    "opcode": 144,
    "mnemonic": "SWAP1",
    "immediateBytes": 0,
    "pops": 0,
    "pushes": 0,
    "staticAllowed": true,
    "stackSignature": "(v1,v0)->(v0,v1)",
    "semantics": "swap top with selected stack word; underflow if absent",
    "width": 1
  },
  {
    "opcode": 145,
    "mnemonic": "SWAP2",
    "immediateBytes": 0,
    "pops": 0,
    "pushes": 0,
    "staticAllowed": true,
    "stackSignature": "(v2,v1,v0)->(v0,v1,v2)",
    "semantics": "swap top with selected stack word; underflow if absent",
    "width": 1
  },
  {
    "opcode": 146,
    "mnemonic": "SWAP3",
    "immediateBytes": 0,
    "pops": 0,
    "pushes": 0,
    "staticAllowed": true,
    "stackSignature": "(v3,v2,v1,v0)->(v0,v2,v1,v3)",
    "semantics": "swap top with selected stack word; underflow if absent",
    "width": 1
  },
  {
    "opcode": 147,
    "mnemonic": "SWAP4",
    "immediateBytes": 0,
    "pops": 0,
    "pushes": 0,
    "staticAllowed": true,
    "stackSignature": "(v4,v3,v2,v1,v0)->(v0,v3,v2,v1,v4)",
    "semantics": "swap top with selected stack word; underflow if absent",
    "width": 1
  },
  {
    "opcode": 148,
    "mnemonic": "SWAP5",
    "immediateBytes": 0,
    "pops": 0,
    "pushes": 0,
    "staticAllowed": true,
    "stackSignature": "(v5,v4,v3,v2,v1,v0)->(v0,v4,v3,v2,v1,v5)",
    "semantics": "swap top with selected stack word; underflow if absent",
    "width": 1
  },
  {
    "opcode": 149,
    "mnemonic": "SWAP6",
    "immediateBytes": 0,
    "pops": 0,
    "pushes": 0,
    "staticAllowed": true,
    "stackSignature": "(v6,v5,v4,v3,v2,v1,v0)->(v0,v5,v4,v3,v2,v1,v6)",
    "semantics": "swap top with selected stack word; underflow if absent",
    "width": 1
  },
  {
    "opcode": 150,
    "mnemonic": "SWAP7",
    "immediateBytes": 0,
    "pops": 0,
    "pushes": 0,
    "staticAllowed": true,
    "stackSignature": "(v7,v6,v5,v4,v3,v2,v1,v0)->(v0,v6,v5,v4,v3,v2,v1,v7)",
    "semantics": "swap top with selected stack word; underflow if absent",
    "width": 1
  },
  {
    "opcode": 151,
    "mnemonic": "SWAP8",
    "immediateBytes": 0,
    "pops": 0,
    "pushes": 0,
    "staticAllowed": true,
    "stackSignature": "(v8,v7,v6,v5,v4,v3,v2,v1,v0)->(v0,v7,v6,v5,v4,v3,v2,v1,v8)",
    "semantics": "swap top with selected stack word; underflow if absent",
    "width": 1
  },
  {
    "opcode": 152,
    "mnemonic": "SWAP9",
    "immediateBytes": 0,
    "pops": 0,
    "pushes": 0,
    "staticAllowed": true,
    "stackSignature": "(v9,v8,v7,v6,v5,v4,v3,v2,v1,v0)->(v0,v8,v7,v6,v5,v4,v3,v2,v1,v9)",
    "semantics": "swap top with selected stack word; underflow if absent",
    "width": 1
  },
  {
    "opcode": 153,
    "mnemonic": "SWAP10",
    "immediateBytes": 0,
    "pops": 0,
    "pushes": 0,
    "staticAllowed": true,
    "stackSignature": "(v10,v9,v8,v7,v6,v5,v4,v3,v2,v1,v0)->(v0,v9,v8,v7,v6,v5,v4,v3,v2,v1,v10)",
    "semantics": "swap top with selected stack word; underflow if absent",
    "width": 1
  },
  {
    "opcode": 154,
    "mnemonic": "SWAP11",
    "immediateBytes": 0,
    "pops": 0,
    "pushes": 0,
    "staticAllowed": true,
    "stackSignature": "(v11,v10,v9,v8,v7,v6,v5,v4,v3,v2,v1,v0)->(v0,v10,v9,v8,v7,v6,v5,v4,v3,v2,v1,v11)",
    "semantics": "swap top with selected stack word; underflow if absent",
    "width": 1
  },
  {
    "opcode": 155,
    "mnemonic": "SWAP12",
    "immediateBytes": 0,
    "pops": 0,
    "pushes": 0,
    "staticAllowed": true,
    "stackSignature": "(v12,v11,v10,v9,v8,v7,v6,v5,v4,v3,v2,v1,v0)->(v0,v11,v10,v9,v8,v7,v6,v5,v4,v3,v2,v1,v12)",
    "semantics": "swap top with selected stack word; underflow if absent",
    "width": 1
  },
  {
    "opcode": 156,
    "mnemonic": "SWAP13",
    "immediateBytes": 0,
    "pops": 0,
    "pushes": 0,
    "staticAllowed": true,
    "stackSignature": "(v13,v12,v11,v10,v9,v8,v7,v6,v5,v4,v3,v2,v1,v0)->(v0,v12,v11,v10,v9,v8,v7,v6,v5,v4,v3,v2,v1,v13)",
    "semantics": "swap top with selected stack word; underflow if absent",
    "width": 1
  },
  {
    "opcode": 157,
    "mnemonic": "SWAP14",
    "immediateBytes": 0,
    "pops": 0,
    "pushes": 0,
    "staticAllowed": true,
    "stackSignature": "(v14,v13,v12,v11,v10,v9,v8,v7,v6,v5,v4,v3,v2,v1,v0)->(v0,v13,v12,v11,v10,v9,v8,v7,v6,v5,v4,v3,v2,v1,v14)",
    "semantics": "swap top with selected stack word; underflow if absent",
    "width": 1
  },
  {
    "opcode": 158,
    "mnemonic": "SWAP15",
    "immediateBytes": 0,
    "pops": 0,
    "pushes": 0,
    "staticAllowed": true,
    "stackSignature": "(v15,v14,v13,v12,v11,v10,v9,v8,v7,v6,v5,v4,v3,v2,v1,v0)->(v0,v14,v13,v12,v11,v10,v9,v8,v7,v6,v5,v4,v3,v2,v1,v15)",
    "semantics": "swap top with selected stack word; underflow if absent",
    "width": 1
  },
  {
    "opcode": 159,
    "mnemonic": "SWAP16",
    "immediateBytes": 0,
    "pops": 0,
    "pushes": 0,
    "staticAllowed": true,
    "stackSignature": "(v16,v15,v14,v13,v12,v11,v10,v9,v8,v7,v6,v5,v4,v3,v2,v1,v0)->(v0,v15,v14,v13,v12,v11,v10,v9,v8,v7,v6,v5,v4,v3,v2,v1,v16)",
    "semantics": "swap top with selected stack word; underflow if absent",
    "width": 1
  },
  {
    "opcode": 160,
    "mnemonic": "LOG0",
    "immediateBytes": 0,
    "pops": 2,
    "pushes": 0,
    "staticAllowed": false,
    "stackSignature": "(size,offset,topic0,...,topicN-1)->()",
    "semantics": "append virtual record using active emitter, topics in topic0..topicN-1 order, and memory[offset:offset+size] data",
    "width": 1
  },
  {
    "opcode": 161,
    "mnemonic": "LOG1",
    "immediateBytes": 0,
    "pops": 3,
    "pushes": 0,
    "staticAllowed": false,
    "stackSignature": "(size,offset,topic0,...,topicN-1)->()",
    "semantics": "append virtual record using active emitter, topics in topic0..topicN-1 order, and memory[offset:offset+size] data",
    "width": 1
  },
  {
    "opcode": 162,
    "mnemonic": "LOG2",
    "immediateBytes": 0,
    "pops": 4,
    "pushes": 0,
    "staticAllowed": false,
    "stackSignature": "(size,offset,topic0,...,topicN-1)->()",
    "semantics": "append virtual record using active emitter, topics in topic0..topicN-1 order, and memory[offset:offset+size] data",
    "width": 1
  },
  {
    "opcode": 163,
    "mnemonic": "LOG3",
    "immediateBytes": 0,
    "pops": 5,
    "pushes": 0,
    "staticAllowed": false,
    "stackSignature": "(size,offset,topic0,...,topicN-1)->()",
    "semantics": "append virtual record using active emitter, topics in topic0..topicN-1 order, and memory[offset:offset+size] data",
    "width": 1
  },
  {
    "opcode": 164,
    "mnemonic": "LOG4",
    "immediateBytes": 0,
    "pops": 6,
    "pushes": 0,
    "staticAllowed": false,
    "stackSignature": "(size,offset,topic0,...,topicN-1)->()",
    "semantics": "append virtual record using active emitter, topics in topic0..topicN-1 order, and memory[offset:offset+size] data",
    "width": 1
  },
  {
    "opcode": 176,
    "mnemonic": "TXACTOR",
    "immediateBytes": 0,
    "pops": 0,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "()->(result0)",
    "semantics": "root authenticated AccountId",
    "width": 1
  },
  {
    "opcode": 177,
    "mnemonic": "WORLDID",
    "immediateBytes": 0,
    "pops": 0,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "()->(result0)",
    "semantics": "current PoolId",
    "width": 1
  },
  {
    "opcode": 178,
    "mnemonic": "EXECUTIONHEIGHT",
    "immediateBytes": 0,
    "pops": 0,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "()->(result0)",
    "semantics": "height assigned to current successful execution candidate",
    "width": 1
  },
  {
    "opcode": 179,
    "mnemonic": "ETHIN",
    "immediateBytes": 0,
    "pops": 0,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "()->(result0)",
    "semantics": "exact outer ETH input",
    "width": 1
  },
  {
    "opcode": 180,
    "mnemonic": "TOKENOUT",
    "immediateBytes": 0,
    "pops": 0,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "()->(result0)",
    "semantics": "gross outer TOKEN output before VM burn",
    "width": 1
  },
  {
    "opcode": 181,
    "mnemonic": "TICK",
    "immediateBytes": 0,
    "pops": 0,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "()->(result0)",
    "semantics": "post-swap int24 tick sign-extended to 256 bits",
    "width": 1
  },
  {
    "opcode": 182,
    "mnemonic": "LIQUIDITY",
    "immediateBytes": 0,
    "pops": 0,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "()->(result0)",
    "semantics": "post-swap active v4 liquidity",
    "width": 1
  },
  {
    "opcode": 183,
    "mnemonic": "BYTEPRICE",
    "immediateBytes": 0,
    "pops": 0,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "()->(result0)",
    "semantics": "immutable TOKEN units per executed byte",
    "width": 1
  },
  {
    "opcode": 184,
    "mnemonic": "BYTESUSED",
    "immediateBytes": 0,
    "pops": 0,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "()->(result0)",
    "semantics": "shared executed-byte count including current opcode",
    "width": 1
  },
  {
    "opcode": 185,
    "mnemonic": "BYTESREMAINING",
    "immediateBytes": 0,
    "pops": 0,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "()->(result0)",
    "semantics": "root byte limit minus bytes used",
    "width": 1
  },
  {
    "opcode": 186,
    "mnemonic": "TXROUTER",
    "immediateBytes": 0,
    "pops": 0,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "()->(result0)",
    "semantics": "EVM Router address bound into the authenticated root action, zero-padded to one word; zero for direct static queries",
    "width": 1
  },
  {
    "opcode": 187,
    "mnemonic": "TXEXECUTOR",
    "immediateBytes": 0,
    "pops": 0,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "()->(result0)",
    "semantics": "EVM authorizedExecutor address bound into the authenticated root action, zero-padded to one word; zero for permissionless relay and direct static queries unless the query caller is used as local read executor",
    "width": 1
  },
  {
    "opcode": 188,
    "mnemonic": "TXRECIPIENT",
    "immediateBytes": 0,
    "pops": 0,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "()->(result0)",
    "semantics": "EVM recipient address bound into the authenticated root action, zero-padded to one word; zero for direct static queries",
    "width": 1
  },
  {
    "opcode": 240,
    "mnemonic": "CREATE",
    "immediateBytes": 0,
    "pops": 3,
    "pushes": 1,
    "staticAllowed": false,
    "stackSignature": "(codeHash,inputSize,inputOffset)->account",
    "semantics": "instantiate registered codeHash with constructor calldata from memory and return AccountId",
    "width": 1
  },
  {
    "opcode": 241,
    "mnemonic": "CALL",
    "immediateBytes": 0,
    "pops": 5,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "(target,inputSize,inputOffset,outputSize,outputOffset)->success",
    "semantics": "call same-World target with memory input; retain full child return data; copy min(outputSize,returnDataSize) bytes to outputOffset; push one; child failure propagates",
    "width": 1
  },
  {
    "opcode": 243,
    "mnemonic": "RETURN",
    "immediateBytes": 0,
    "pops": 2,
    "pushes": 0,
    "staticAllowed": true,
    "stackSignature": "(size,offset)->halt",
    "semantics": "successful frame halt with memory output",
    "width": 1
  },
  {
    "opcode": 250,
    "mnemonic": "STATICCALL",
    "immediateBytes": 0,
    "pops": 5,
    "pushes": 1,
    "staticAllowed": true,
    "stackSignature": "(target,inputSize,inputOffset,outputSize,outputOffset)->success",
    "semantics": "CALL with static flag inherited by descendants and identical return-data handling",
    "width": 1
  },
  {
    "opcode": 253,
    "mnemonic": "REVERT",
    "immediateBytes": 0,
    "pops": 2,
    "pushes": 0,
    "staticAllowed": true,
    "stackSignature": "(size,offset)->halt",
    "semantics": "revert complete root execution with memory error data",
    "width": 1
  }
] as const;
