// Generated by scripts/generate-compiler-identity.mjs. Do not edit manually.
export const COMPILER_SOURCE_FINGERPRINT = "0xe4609dd802f2e33655aa982e481e46495247d464a776738a93d77fb947bbee09" as const;
export const COMPILER_DEPENDENCY_LOCK_SHA256 = "9fc12a680b184df64106253992b39e208b10fd27612830c1514affe6f03878eb" as const;
