// Generated by scripts/generate-compiler-identity.mjs. Do not edit manually.
export const COMPILER_SOURCE_FINGERPRINT = "0x21ac26b8519584580ec6ff8d3759b22e8f07ede2f5d2da76c613911b60b2ebd4" as const;
export const COMPILER_DEPENDENCY_LOCK_SHA256 = "a89b9a20d3d196d5c7b00960aa885ac8e750b20974294c51c07b6c32fac2a8d1" as const;
